server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/menudb
    username: swcamp
    password: swcamp

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    com:
      ohgiraffers:
        springdatajpa: debug