server:
  port: 8001

spring:
  application:
    name: eureka-client

eureka:
  client:

    # 서버에 등록한다
    register-with-eureka: true

    # 30초마다 상태 체크
    fetch-registry: true

    # eureka server 주소
    service-url:
      defaultZone: http://localhost:8761/eureka